"""first init

Revision ID: 0c36f56441f7
Revises: 
Create Date: 2025-10-23 22:23:46.526302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c36f56441f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_progress')
    op.drop_index(op.f('ix_user_book_user_id'), table_name='user_books')
    op.drop_table('user_books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_books',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_books_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('overall_progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.CheckConstraint('overall_progress >= 0.0::double precision AND overall_progress <= 1.0::double precision', name='check_overall_progress_range'),
    sa.PrimaryKeyConstraint('id', name='user_books_pkey'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_user_book', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_user_book_user_id'), 'user_books', ['user_id'], unique=False)
    op.create_table('reading_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_book_id'], ['user_books.id'], name=op.f('reading_progress_user_book_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reading_progress_pkey'))
    )
    # ### end Alembic commands ###
