"""fix_foreign_key_cascade

Revision ID: e185fab7898b
Revises: c1d638056fa2
Create Date: 2026-01-01 19:24:44.097630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e185fab7898b'
down_revision: Union[str, Sequence[str], None] = 'c1d638056fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reading_progress_user_book_id_fkey'), 'reading_progress', type_='foreignkey')
    op.create_foreign_key(None, 'reading_progress', 'user_books', ['user_book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reading_progress', type_='foreignkey')
    op.create_foreign_key(op.f('reading_progress_user_book_id_fkey'), 'reading_progress', 'user_books', ['user_book_id'], ['id'])
    # ### end Alembic commands ###
